### ISSUE TITLE
Your library would be more useful is you separated the IO operations from it

### ISSUE THREAD

**Issue by jratcliff63367** [wookjinAhn/KMeansClustering#1]
This is really just some advice if you would like people to use your library. Your code which computes Kmeans should do just that. Period. Nothing more. It shouldn't have code to read and write stuff to and from disk or anything like that. That logic should be placed elsewhere in a separate file. Overall the code is clear and easy to read but minimizing dependencies and extraneous stuff like file IO would be a better design.

At any rate, thanks for uploading the code it's a nice reference.

**Comment by wookjinahn** [comment]
Thanks for your advice on considering dependencies.
I'm just starting, so I needed some advices like yours.
Thanks a lot.
